### PR TITLE
Migrate from TSLint to ESLint and fix violations

### PR DESCRIPTION
**Pull request by vishal423**
- Migrate from TSLint to ESLint and use shareable config
- Fix violations reported by ESLint rules
- Fix travis pipeline

### CODE REVIEW

**Comment by vishal423** [comment]
@jhipster/developers, this PR is ready for review.

**Comment by vishal423** [comment]
ping @jhipster/developers

**Comment by MathieuAA** [comment]
LGTM

**Comment by vishal423** [comment]
thanks @MathieuAA for review. I think we should also do a new library release to integrate this change on main.

**Pull request merged**
