### PR TITLE
Add data-utils for blob support

### PR DESCRIPTION
**Pull request by agaspardcilia**
A Reactized copy of [this](https://github.com/jhipster/ng-jhipster/blob/master/src/service/data-util.service.ts).

### CODE REVIEW

**Comment by deepu105** [comment]
can you add a test for it please, since its the lib we should ensure test coverage as much as possible

**Comment by agaspardcilia** [comment]
Alright

**Comment by agaspardcilia** [comment]
The angular one isn't testing much.

**Comment by deepu105** [comment]
v 0.4.5 released please use it in the other PR

**Pull request merged**
