### PR TITLE
Drop bundles.

### PR DESCRIPTION
**Pull request by mshima**
I don't think bundles are useful anymore.
Reduces package size from `1,5M` to `83K`.
```
-rw-r--r--    1 mshima  staff   1,5M  5 Out 10:39 react-jhipster-0.16.2-bundle.tgz
-rw-r--r--    1 mshima  staff    83K  5 Out 10:37 react-jhipster-0.16.2-no-bundle.tgz
```

Closes https://github.com/jhipster/react-jhipster/pull/73.

### CODE REVIEW

**Review by deepu105 — APPROVED** [review]
Ya the bundle was added when modules were weird and flaky. If it works from soutrce using the webpack setup in the parent app it should be good

**Comment by deepu105** [comment]
@mshima can we close the other PR in favor of this?

**Comment by mshima** [comment]
@deepu105 of corse.
I’ve splitted due to the breaking change nature.

**Comment by mshima** [comment]
@pascalgrimaud for safety better to bump to v0.17.x due to bundles drop.

**Comment by pascalgrimaud** [comment]
Thanks @deepu105 and @mshima : https://github.com/jhipster/generator-jhipster/pull/16572

**Pull request merged**
