### PR TITLE
add pagination params to ICrudSearchAction

### PR DESCRIPTION
**Pull request by ruddell**
related to jhipster/generator-jhipster#8776

### CODE REVIEW

**Comment by ruddell** [comment]
Test failures from the first commit are due to unpinned versions in package.json, we didn't have a package-lock.json yet

**Comment by ruddell** [comment]
Their fix looks better since it actually fixes the dependency issue, so I'll revert my changes to the package.json.  This change is simple and doesn't break any tests

**Comment by deepu105** [comment]
Plz merge when green. Also remind me to make a release when merged

**Comment by ruddell** [comment]
@deepu105 Merged, please make a release when you find time

**Comment by deepu105** [comment]
Done releases both angular and react lib, could you plz update the generator

Thanks & Regards,
Deepu

**Pull request merged**
