### PR TITLE
Add item count component

### PR DESCRIPTION
**Pull request by clement26695**
Add itemCount Component as it exists on the Angular library 

linked to jhipster/generator-jhipster#9678

### CODE REVIEW

**Comment by clement26695** [comment]
I'm not sure how to handle translation, here. Is there a way to notify the component that i18n is enabled or not ?

**Comment by pascalgrimaud** [comment]
@clement26695 : does it work with i18n and without i18n ?
I'm not a React guy so I don't have the answer for your question...

Maybe @chrisdns you can help ?

**Comment by chrisdns** [comment]
Not sure how you can tell to this component if i18n is enabled, as it is done in angular, since it is related to the project generation and I dont see how to do it in react way.
Maybe doing something in the `Translate` component like "if the translate key does not exists, show the inner html, else display the translation" might work, this should not change the current translation behaviour of a generated project

**Comment by clement26695** [comment]
I think it is ok: there is an "enableTranslation" variable in the entity template that we can use to tell that i18n is enabled

**Pull request merged**
