### PR TITLE
Fix React+NPM applications

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Similar to this PR: https://github.com/jhipster/generator-jhipster/pull/8183
Related to https://github.com/jhipster/generator-jhipster/issues/8162

Otherwise, I encounter some errors during `npm test`, that I don't have with Yarn.
It seems Yarn is better than NPM for managing dependencies - cc @PierreBesson

### CODE REVIEW

**Comment by PierreBesson** [comment]
Well, maybe you need to upgrade the package-lock as well by deleting the node_modules and running npm install.

**Comment by pascalgrimaud** [comment]
This project uses Yarn for now, not yet NPM.
Need to migrate too maybe ?

**Comment by jdubois** [comment]
Yes if we migrate the generator to Yarn, we should also migrate all sub-projects.

**Comment by pascalgrimaud** [comment]
It's planned, I prefer to do step by step

**Comment by pascalgrimaud** [comment]
this PR is just to be consistent, with main generator-jhipster
The issue I got, was `npm test -- -u` not with dependencies here

**Pull request merged**
