### PR TITLE
Add Missing Required Statement to Load the Correct Locale

### PR DESCRIPTION
**Pull request by SudharakaP**
As per numeraljs 2.0.0 we have to load the locale file; https://github.com/adamwdraper/Numeral-js#200

Fixes https://github.com/jhipster/generator-jhipster/issues/11561, Fixes https://github.com/jhipster/react-jhipster/issues/47

### CODE REVIEW

**Comment by atomfrede** [comment]
Does this load all locales supported by numerals.js

**Comment by deepu105** [comment]
We are not adding locales for numeral current. I noticed it yesterday. I'll
do a PR to atleast expose the numerals instance to add locale config. Also
we need to document the numerals support

**Comment by deepu105** [comment]
@SudharakaP I saw your question on Gitter regarding the lib, we checkin the lib so that its included in the npm distribution, there was issue with NPM back then where it was skipping everything in gitignore as well, not sure if the problem still exists.

For the metrics, when I did the lib we were not translating those parts, if we want them translated it should be as easy as adding the translate directive on those since its comes for the lib anyway

**Comment by SudharakaP** [comment]
@deepu105 :

> I noticed it yesterday as well. I'll do a PR to expose the numerals instance as well to add locale config if required. Also we need to document the numerals support

Do you mean loading the numerals as needed instead of all of them? 

> @SudharakaP I saw your question on Gitter regarding the lib, we checkin the lib so that its included in the npm distribution, there was issue with NPM back then where it was skipping everything in gitignore as well, not sure if the problem still exists.
> 
> For the metrics, when I did the lib we were not translating those parts, if we want them translated it should be as easy as adding the translate directive on those since its comes for the lib anyway

Thanks for the explanation. :+1:

**Comment by deepu105** [comment]
@SudharakaP no, just to expose the numerals instance so that users can configure custom settings if needed. But it would be nice to load only needed locales as well to reduce bundle size unless they tree shake well

**Comment by SudharakaP** [comment]
> @SudharakaP no, just to expose the numerals instance so that users can configure custom settings if needed. But it would be nice to load only needed locales as well to reduce bundle size unless they tree shake well

Hmm... :thinking: I'll try to think of a way to do the numerals loading as per needed, but can't be sure I'll find one; spent some time on this previously and I didn't find a way to dynamically load the relevant locales. If anyone has an idea feel free to let me know. :smile:

**Comment by pascalgrimaud** [comment]
@deepu105 @SudharakaP : what is the state of this PR ? Can it be merged ? It would be cool to have this for fixing the original issue with metrics page for React

**Comment by SudharakaP** [comment]
@pascalgrimaud : It does solve the original issue of fixing the metrics page I think and therefore can be merged. 

But the more optimized solution of loading locales dynamically; I couldn't figure out a method unfortunately. Hopefully someone else can chip in on that. :disappointed:

**Comment by pascalgrimaud** [comment]
Ok then, so let's merge this.
I'll do a release of this project and we can do a patch release if it's improved the next 2 or 3 days

**Comment by SudharakaP** [comment]
Bug bounty submitted at https://opencollective.com/generator-jhipster/expenses/17500

**Pull request merged**
