### PR TITLE
allow passing default sort order in react projects

### PR DESCRIPTION
**Pull request by OmarHawk**
fixes jhipster/generator-jhipster#17849

### CODE REVIEW

**Review by deepu105 — APPROVED** [review]
Looks good

**Comment by OmarHawk** [comment]
> Looks good

Thanks. :-)

**Comment by OmarHawk** [comment]
@DanielFran , maybe this can then be merged? :)

**Comment by DanielFran** [comment]
Thanks @OmarHawk for the contribution
We will need now the proper changes on generator project

**Comment by pascalgrimaud** [comment]
Will do it for the next release of generator-jhipster

**Comment by OmarHawk** [comment]
> Thanks @OmarHawk for the contribution We will need now the proper changes on generator project

Well, the change here should be backwards compatible as the added param is optional (with the proper default value) :-)

**Pull request merged**
