### PR TITLE
Remove require of dayjs modules

### PR DESCRIPTION
**Pull request by swarajsaaj**
Remove redundant importing of dayjs modules as they are already imported
at
https://github.com/jhipster/generator-jhipster/blob/c46dbd7b56c844699918e2733e3c5560dcba1ddd/generators/generator-base-private.js#L361

Fix jhipster/generator-jhipster#16486

### CODE REVIEW

**Comment by mshima** [comment]
I don’t think this will be enough to fix this problem.
Locale would have to match the id for dayjs, numeral and angular.
https://github.com/jhipster/react-jhipster/blob/911900d50b9dc03740869fc6fcf84e1c4675cf21/src/formatter/text-format.tsx#L32-L56

I think we would have to create a structure to store locale id for each lib.

**Comment by swarajsaaj** [comment]
@mshima I agree, will refactor to pass a larger language object (with all defined standard locales).
On a separate note, do you feel  require statements like `require('dayjs/locale/' + locale + '.js'); `  should be added in code even if they are already done in `dayjs.ts` (app/config/dayjs.ts)?

**Comment by mshima** [comment]
@swarajsaaj yes, sure.
But see the above snippet, there is another `require`, you will probably want to remote that too.

**Comment by swarajsaaj** [comment]
@mshima  Removed the extra `require` in https://github.com/jhipster/react-jhipster/blob/911900d50b9dc03740869fc6fcf84e1c4675cf21/src/formatter/text-format.tsx#L43

For overall refactoring of locale, (using an composition object of isoLocale, angularLocale, javaLocale and library specific locales)  I think it should be first done in `generator-jhipster` maybe as a part of separate PR?

**Review by mshima — APPROVED** [review]
LGTM

**Pull request merged**
