### PR TITLE
Cleanup dependencies.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/16527.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
We need your reviews / tests if possible plz, @deepu105 @ctamisier @Jackjun724

**Comment by ctamisier** [comment]
LGTM

I've tried the following steps.

First:
`npm install -g npm@latest`

Then in _react-jhipster_:
`npm install` -> **works**
`npm test` -> **works**
`npm ci` -> **works**
`npm run build` -> **works**

Then in the host project (e.g. generated app):
`npm install ../react-jhipster/react-jhipster-0.16.2.tgz` (after `npm pack` in react-jhipster)
`npm install` -> **works**
`npm test` -> **works**
`npm run webapp:build` -> **works**

If I drop peerDependencies in _react-jhipster_, I have the same exact behavior (Maybe I'm missing something..).
About the potential `jest` conflict (I don't know how to "reproduce" it), maybe there is no problem as it is a devDependency ?(and not a dependency).. BTW I'm far to understand everything about npm and  its dependency management

**Comment by Jackjun724** [comment]
It seems that there is no problem, but I think the root cause of the problem is `"react-transition-group": "^4.4.1"` is tool dependency instead of ​core dependency, So it shouldn't be `peerDependency`, `jest` it seems to be a potential conflict.

**Comment by mshima** [comment]
> If I drop peerDependencies in _react-jhipster_, I have the same exact behavior (Maybe I'm missing something..).
> About the potential `jest` conflict (I don't know how to "reproduce" it), maybe there is no problem as it is a devDependency ?(and not a dependency).. BTW I'm far to understand everything about npm and its dependency management

@ctamisier remove peerDependencies and try to recreate the package-lock.json with npm@7 and it will show peer conflicts.
```
rm -rf node_modules package-lock.json
npx npm@7 install # if you have npm@6 globally
```

`react-transition-group` was removed from package.json. It isn't used directly, it's a transitive dependency of `reactstrap`.

**Comment by ctamisier** [comment]
I don't get it as we don't have the same result. I'll keep investigating.
But for the release I'd say everything is ok.

image

**Comment by mshima** [comment]
> I don't get it as we don't have the same result. I'll keep investigating. But for the release I'd say everything is ok.

Looks like are using my branch or another one, see the `react-transition-group` that existing in main and doesn't appears at the diff.

**Comment by mshima** [comment]
@ctamisier are you proposing to drop peer dependencies?
IMO it's important to keep it for derived projects.

**Comment by mshima** [comment]
I've reverted the bundle change, so we don't need to bump to 0.17.x

Is bundles used somewhere?
IMO we should drop it, bundles have been replaced with tree-shaking.
The cleaner a project is, the easier is to maintain.

**Comment by ctamisier** [comment]
> @ctamisier are you proposing to drop peer dependencies?
IMO it's important to keep it for derived projects.

Removing peerDependencies on your branch is working.
Removing peerDependencies on `main` is failing (but it was also failing when we keep them (fails only when doing `rm -rf node_modules package-lock.json`)

I think you know way more than me about all this, so yes let's keep peerDependencies. (I really don't know the impact by dropping them, just because of my limited knowledge about this). I was just seeing that removing peerDependenciies was **also** working on your branch.

**Review by deepu105 — APPROVED** [review]
Looks good. If those deps are not required anymore. Keeping peer deps would be a good idea

**Pull request closed without merging**
