### PR TITLE
Upgrade React 18

### PR DESCRIPTION
**Pull request by qmonmert**
Need for https://github.com/jhipster/generator-jhipster/issues/18416

### CODE REVIEW

**Comment by qmonmert** [comment]
it seems that there are bugs with reactstrap
image

**Comment by DanielFran** [comment]
Blocked due to https://github.com/reactstrap/reactstrap/pull/2502

**Comment by qmonmert** [comment]
@DanielFran PR merged on Reactstrap, we wait a new release of reactstrap

**Comment by DanielFran** [comment]
@qmonmert Seems it will be done today: https://github.com/reactstrap/reactstrap/pull/2530

**Comment by DanielFran** [comment]
@qmonmert v.9.0.3 is now available ;)

**Comment by DanielFran** [comment]
@Trusting on you for this

**Review by DanielFran — APPROVED** [review]

**Comment by qmonmert** [comment]
@DanielFran ok we will need a release for the generator

**Comment by DanielFran** [comment]
cc @pascalgrimaud

**Comment by mshima** [comment]
We can use git dependency for now.

**Comment by pascalgrimaud** [comment]
@DanielFran : you should be able to publish a new version of this lib, you're admin

**Comment by deepu105** [comment]
Don't hesitate to ask for more bounty if the work is more

**Comment by qmonmert** [comment]
can we release a new version?

**Comment by mshima** [comment]
@qmonmert you can use git version:
```
  "react-jhipster": "jhipster/react-jhipster",
```

We've done that and release react-jhipster together with generator-jhipster last cycle.

**Comment by antonioorct** [comment]
Installing the git version package, doesn't build the library. It keeps the files the same as the current repo's `/lib` folder and thus it's using a previous version of react-jhipster and no typescript

**Pull request merged**
