### PR TITLE
Do not show translation until translation data has loaded

### PR DESCRIPTION
**Pull request by windkomo**
Fix https://github.com/jhipster/generator-jhipster/issues/8633

As I understand it, `translationData` is an empty object if translations have not loaded yet, so we can return `null` as content.

I did not use a CSS class because to me, this behavior comes from underlying data loading state and should not be solve using a "styling" solution.

### CODE REVIEW

**Comment by deepu105** [comment]
LGTM, will test soon

**Comment by deepu105** [comment]
@windkomo can you add a unit test please

**Comment by pascalgrimaud** [comment]
I tried to test this PR, I encounter some issue with `npm link`.
What I do:
- git checkout pr/17
- npm install
- npm link
- go into a fresh generated React project
- npm install
- npm link react-jhipster
- npm  run webpack:build

I got all these errors/warnings:
```
 ERROR  Failed to compile with 2 errors                                                                                                                                                16:41:48

 error  in /home/pgrimaud/projects/jhipster/react-jhipster/src/formatter/text-format.tsx

ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/formatter/text-format.tsx(28,19):
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof moment' has no compatible call signatures.

 error  in /home/pgrimaud/projects/jhipster/react-jhipster/src/language/translate.tsx

ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/language/translate.tsx(109,21):
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof sanitize' has no compatible call signatures.

   1125 modules

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/data-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'data-utils.js.map': Error: Can't resolve './data-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/dom-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'dom-utils.js.map': Error: Can't resolve './dom-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/formatter/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/formatter'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/log-util.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'log-util.js.map': Error: Can't resolve './log-util.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component/pagination/pagination-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'pagination-utils.js.map': Error: Can't resolve './pagination-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component/pagination'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/pagination-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'pagination-utils.js.map': Error: Can't resolve './pagination-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component/pagination/pagination.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'pagination.js.map': Error: Can't resolve './pagination.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/component/pagination'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/promise-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'promise-utils.js.map': Error: Can't resolve './promise-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/storage-util.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'storage-util.js.map': Error: Can't resolve './storage-util.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/formatter/text-format.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'text-format.js.map': Error: Can't resolve './text-format.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/formatter'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language/translate.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'translate.js.map': Error: Can't resolve './translate.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language/translator-context.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'translator-context.js.map': Error: Can't resolve './translator-context.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/language'

WARNING in /home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util/url-utils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'url-utils.js.map': Error: Can't resolve './url-utils.js.map' in '/home/pgrimaud/projects/jhipster/react-jhipster/lib/src/util'

ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/formatter/text-format.tsx
ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/formatter/text-format.tsx(28,19):
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof moment' has no compatible call signatures.

ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/language/translate.tsx
ERROR in /home/pgrimaud/projects/jhipster/react-jhipster/src/language/translate.tsx(109,21):
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof sanitize' has no compatible call signatures.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jhipster@0.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jhipster@0.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pgrimaud/.npm/_logs/2018-11-11T15_41_48_331Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jhipster@0.0.0 webpack:build:main: `npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jhipster@0.0.0 webpack:build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pgrimaud/.npm/_logs/2018-11-11T15_41_48_354Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jhipster@0.0.0 webpack:build: `npm run cleanup && npm run webpack:build:main`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jhipster@0.0.0 webpack:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pgrimaud/.npm/_logs/2018-11-11T15_41_48_366Z-debug.log
```

**Comment by pascalgrimaud** [comment]
Forget my comment, I didn't run `npm run build` as mentionned in README.
Just tested and it works fine!

Thanks @windkomo !

**Comment by windkomo** [comment]
I've claimed the bounty: https://opencollective.com/generator-jhipster/expenses/5717

**Comment by jdubois** [comment]
Thanks @windkomo , bounty paid :-)

**Pull request merged**
